// The "build" step for this repo's design-sync run.
//
// This is a Next.js app, not a published component package: there is no library
// build, no dist/, and npm never self-installs a package into its own
// node_modules. Two things have to exist before package-build.mjs can run:
//
//  1. node_modules/website -> the repo root. The converter resolves the DS at
//     `node_modules/<cfg.pkg>`; without this it dies on ENOENT reading that
//     package.json. This is the same shape npm workspaces would create, and it
//     puts the converter on its documented synth-entry path (no dist, so it
//     synthesizes an entry from src/components — see cfg.srcDir).
//  2. .design-sync/build/ds.css (cfg.cssEntry). src/app/globals.css is Tailwind
//     v4 source (@import "tailwindcss", @theme, @apply) and means nothing to a
//     browser until compiled.
//
// Both are idempotent. The symlink is inside node_modules, so it is NOT
// committed — re-run this script after a fresh clone or install.
//
//   node .design-sync/build-prepare.mjs
import { execFileSync } from 'node:child_process';
import {
  existsSync, mkdirSync, lstatSync, symlinkSync, unlinkSync,
  readdirSync, readFileSync, writeFileSync,
} from 'node:fs';
import { dirname, extname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');

// ── 1. self-link so `node_modules/website` resolves to the repo ──────────
const LINK = join(ROOT, 'node_modules/website');
if (!existsSync(join(ROOT, 'node_modules'))) {
  console.error('[PREPARE] node_modules missing — run `npm ci` first');
  process.exit(1);
}
try {
  if (lstatSync(LINK, { throwIfNoEntry: false })) unlinkSync(LINK);
} catch { /* not a link we own — symlinkSync below will report it */ }
symlinkSync(ROOT, LINK, 'dir');
console.error(`[PREPARE] node_modules/website -> ${ROOT}`);

// ── 2. inline public/ assets the components reference by URL path ───────
// Logo renders src="/logo-navy.png", which Next serves out of public/. In the
// bundle nothing serves that path, so it would 404 in every preview card and
// in every design built with the DS. Emit them as data URIs for the
// next/image shim to look up.
const PUBLIC = join(ROOT, 'public');
const MIME = { '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.svg': 'image/svg+xml', '.webp': 'image/webp' };
const assets = existsSync(PUBLIC)
  ? readdirSync(PUBLIC).filter((f) => extname(f).toLowerCase() in MIME)
  : [];
const entries = assets.map((f) => {
  const data = readFileSync(join(PUBLIC, f));
  return `  ${JSON.stringify('/' + f)}: "data:${MIME[extname(f).toLowerCase()]};base64,${data.toString('base64')}",`;
});
mkdirSync(join(HERE, 'shims'), { recursive: true });
writeFileSync(
  join(HERE, 'shims/public-assets.ts'),
  '// GENERATED by .design-sync/build-prepare.mjs — do not edit.\n' +
    '// public/ assets inlined as data URIs so components that reference them by\n' +
    '// URL path still render outside Next. Keyed by their public/ URL path.\n' +
    'export const PUBLIC_ASSETS: Record<string, string> = {\n' +
    entries.join('\n') +
    '\n};\n',
);
console.error(`[PREPARE] inlined ${assets.length} public/ asset(s) -> shims/public-assets.ts`);

// ── 3. regenerate the utility safelist ──────────────────────────────────
execFileSync(process.execPath, [join(HERE, 'gen-safelist.mjs')], { cwd: ROOT, stdio: 'inherit' });

// ── 4. compile the Tailwind stylesheet ──────────────────────────────────
const CLI = join(ROOT, '.ds-sync/node_modules/@tailwindcss/cli/dist/index.mjs');
if (!existsSync(CLI)) {
  console.error(
    `[PREPARE] tailwind CLI not staged at ${CLI}\n` +
      `          run: (cd .ds-sync && npm i @tailwindcss/cli)`,
  );
  process.exit(1);
}
mkdirSync(join(HERE, 'build'), { recursive: true });
execFileSync(
  process.execPath,
  [CLI, '-i', join(HERE, 'ds-entry.css'), '-o', join(HERE, 'build/ds.css')],
  { cwd: ROOT, stdio: 'inherit' },
);
