// Fetches the brand webfonts the app loads via next/font/google (Fraunces,
// Urbanist) and writes a self-contained @font-face sheet + local .woff2 files.
// next/font resolves these at build time inside Next, so nothing ships in a
// plain browser bundle — design-sync needs real files. Re-run with:
//   node .design-sync/fetch-fonts.mjs
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, 'fonts');
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Axes mirror src/app/layout.tsx: Fraunces 400..700 normal; Urbanist 100..900
// normal + italic. subsets: ["latin"] there, so we keep only the latin block.
const API =
  'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400..700' +
  '&family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap';

mkdirSync(OUT, { recursive: true });

const css = await (await fetch(API, { headers: { 'User-Agent': UA } })).text();

// Google emits one commented block per subset; keep the latin ones only.
const blocks = css.split(/\/\*\s*([a-z-]+)\s*\*\//i).slice(1);
const out = [];
for (let i = 0; i < blocks.length; i += 2) {
  const subset = blocks[i];
  const face = blocks[i + 1];
  if (subset !== 'latin') continue;

  const url = face.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;
  const family = face.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font';
  const style = /font-style:\s*italic/.test(face) ? 'italic' : 'normal';
  const file = `${family.toLowerCase()}-latin-${style}.woff2`;

  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(join(OUT, file), buf);
  out.push(face.trim().replace(/url\(https:[^)]+\.woff2\)/, `url(./${file})`));
  console.error(`fetched ${file} (${(buf.length / 1024).toFixed(1)} KB)`);
}

if (!out.length) throw new Error('no latin @font-face blocks found — the Google Fonts API response changed');

writeFileSync(
  join(OUT, 'brand-fonts.css'),
  `/* Brand webfaces for the BEE² design system.\n` +
    `   Generated by .design-sync/fetch-fonts.mjs from Google Fonts (latin subset),\n` +
    `   mirroring the next/font/google config in src/app/layout.tsx. */\n\n` +
    out.join('\n\n') +
    '\n',
);
console.error(`wrote ${out.length} @font-face rules -> fonts/brand-fonts.css`);
